# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# @baseUrl = https://localhost:5001/api # controller commands/queries (/api/users)
@baseUrl = https://localhost:5001 
# endpoint commands/queries (/users)

###################################################################################
#### command, no response (ignored)
# @name user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "FirstName" : "John",
    "LastName" : "Doe{{$randomInt 10 99}}"
}

### capture location
@userRoute = {{user.response.headers.Location}}

###################################################################################
#### command, bad request due to invalid json
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "FirstName" : "John", // this comment causes deserialization error > bad request
    "LastName" : "Doe"
}

###################################################################################
#### command, bad request due to validator
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "FirstName" : "",
    "LastName" : ""
}

###################################################################################
#### command, no response
PUT {{baseUrl}}{{userRoute}} HTTP/1.1
Content-Type: application/json

{
    "FirstName" : "Johny",
    "LastName" : "Doe"
}

###################################################################################
#### command, response
GET {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

###################################################################################
#### command, response
GET {{baseUrl}}{{userRoute}} HTTP/1.1
Content-Type: application/json

###################################################################################
#### command, response TODO=404
GET {{baseUrl}}/users/unk HTTP/1.1
Content-Type: application/json

###################################################################################
#### command, response=404
GET {{baseUrl}}/unk HTTP/1.1
Content-Type: application/json

###################################################################################
#### command, response 500
GET {{baseUrl}}/users/error HTTP/1.1
Content-Type: application/json